missed a hardcoded path

diff --git a/recipe/patches/0000-use-packmol-from-path.patch b/recipe/patches/0000-use-packmol-from-path.patch
--- a/recipe/patches/0000-use-packmol-from-path.patch
+++ b/recipe/patches/0000-use-packmol-from-path.patch
@@ -15,3 +15,16 @@ index 2a80016..bbfff58 100644
          if occursin("Success!", String(take!(log)))
              check_mind(input_test)
          else
+diff --git a/testing/test_failed.sh b/testing/test_failed.sh
+index 9cf19f9..ae6471a 100755
+--- a/testing/test_failed.sh
++++ b/testing/test_failed.sh
+@@ -12,7 +12,7 @@ if ! [ -f $1 ]; then
+     echo "Error: input file not found: $1"
+     exit 1
+ fi
+-../packmol < $1 > $2
++packmol < $1 > $2
+ if ! [ -f $2 ]; then
+     echo "Error: Log file not generated: $2"
+     exit 1
